name: Build StreetRush

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get project
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          

      - name: Install dependencies
        run: npm install

      - name: Build StreetRush
        run: npm run build

      - name: Upload web build
        uses: actions/upload-artifact@v4
        with:
          name: StreetRush-build
          path: dist
